# 1. What is a Python library? Why do we use Python libraries?

A Python library is a collection of functions and methods that allows you to perform many actions without writing your own code.

We use Python Libraries for -

* Reusability: Libraries provide pre-written code for common tasks, allowing developers to avoid reinventing the wheel. This saves time and effort, promoting code efficiency and maintainability.

* Functionality: Libraries extend Python's capabilities beyond its built-in functions. They offer specialized tools and algorithms for various domains such as data analysis, machine learning, web development, scientific computing, and more.

* Community Contribution: Python libraries are often open-source and developed collaboratively by a community of programmers. This results in high-quality, well-tested code that benefits from collective expertise and continuous improvement.

* Performance: Many Python libraries are implemented in efficient, compiled languages like C or C++, which can significantly improve performance compared to pure Python implementations.

* Integration: Libraries provide interfaces to interact with external services, APIs, and databases, enabling seamless integration of Python applications with other software systems.

* Standardization: Popular libraries often establish de facto standards and best practices within their respective domains, fostering consistency and interoperability among developers.

# Examples of Python Libraries:
*  NumPy: For numerical computing with arrays and matrices.
* Pandas: For data manipulation and analysis.
* Matplotlib and Seaborn: For data visualization.
* Requests: For making HTTP requests.
* Scikit-learn: For machine learning tasks.
* Django and Flask: For web development.


# 2. What is the difference between Numpy array and List?

* Homogeneity vs. Heterogeneity: NumPy arrays are homogeneous and contain elements of the same data type, whereas lists in Python can contain elements of different data types.

* Performance: NumPy arrays are more efficient for numerical operations due to their fixed type and optimized memory layout (contiguous block of memory), which allows for faster computation compared to lists.

* Functionality: NumPy arrays provide extensive mathematical functions and operations tailored for numerical computing, while lists offer general-purpose data storage with more flexibility in terms of data types and operations.

# 3. Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [23]:
import numpy as np
array = [[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 10, 11, 12]]

num_rows = len(arr)
num_cols = len(arr[0])

#shape of array
shape = (num_rows,num_cols)
print("Shape of the array:" ,shape)

#size of array
size = num_rows*num_cols
print("size of the array:",size)



Shape of the array: (3, 4)
size of the array: 12


In [21]:
import numpy as np

# Example NumPy array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Find the dimension of the array
dimension = arr.ndim

print("Dimension:", dimension)  

Dimension: 2


# 4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [24]:
import numpy as np

# Example NumPy array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Access the first row 
first_row = arr[0]

print("First Row (NumPy array):", first_row)  


First Row (NumPy array): [1 2 3 4]


# 5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [25]:
import numpy as np

# Given NumPy array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Access the element at the third row (index 2) and fourth column (index 3)
element = arr[2, 3]

print("Element at third row and fourth column:", element)  


Element at third row and fourth column: 12


# 6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [30]:
import numpy as np

# Given NumPy array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Extract all odd-indexed elements
odd_indexed_elements = arr[:, 1::2].flatten()

print("Odd-indexed elements:", odd_indexed_elements)


Odd-indexed elements: [ 2  4  6  8 10 12]


# 7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [31]:
import numpy as np

# Generate a random 3x3 matrix with values between 0 and 1
random_matrix = np.random.rand(3, 3)

print("Random 3x3 matrix:")
print(random_matrix)


Random 3x3 matrix:
[[0.40543251 0.93229598 0.85761681]
 [0.61233689 0.88360984 0.31839513]
 [0.67027704 0.00626277 0.20865457]]


# 8.Describe the difference between np.random.rand and np.random.randn?

The functions np.random.rand and np.random.randn are both used in NumPy to generate arrays with random numbers, but they have key differences in how they distribute those random numbers.

# np.random.rand
* Distribution: Generates random values from a uniform distribution over the interval [0, 1).
* Syntax: np.random.rand(d0, d1, ..., dn)
# np.random.randn
* Distribution: Generates random values from a standard normal distribution (mean 0, standard deviation 1).
* Syntax: np.random.randn(d0, d1, ..., dn)
* Generates an array of shape (d0, d1, ..., dn) where each element is drawn from a standard normal distribution (mean 0, standard deviation 1).

In [32]:
#e.g to show np.random.rand

import numpy as np

# Generate a 2x3 array of random numbers between 0 and 1
arr_rand = np.random.rand(2, 3)

print(arr_rand)


[[0.78288326 0.87651432 0.840963  ]
 [0.47102142 0.49600356 0.87411343]]


In [33]:
# e.g to show np.random.randn

import numpy as np

# Generate a 2x3 array of random numbers from a standard normal distribution
arr_randn = np.random.randn(2, 3)

print(arr_randn)


[[-1.78259496  2.4947047  -2.04618377]
 [ 0.48426219  1.57398176 -0.28209986]]


# 9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [34]:
import numpy as np

# Given NumPy array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Method 1: Using np.newaxis to add a new axis (dimension)
expanded_arr = arr[:, :, np.newaxis]

print("Original Array Shape:", arr.shape)        
print("Expanded Array Shape:", expanded_arr.shape)  


Original Array Shape: (3, 4)
Expanded Array Shape: (3, 4, 1)


# 10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [35]:
import numpy as np

# Given NumPy array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])


transposed_arr = np.transpose(arr)

print("Original Array:")
print(arr)

print("\nTransposed Array:")
print(transposed_arr)


Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transposed Array:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


# 11. Consider the following matrix:
Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Perform the following operation using Python1

1. index wise multiplication

2. Matix multiplication

3. Add both the matics

4. Subtact matrix B from A

5. Diide Matrix B by A

In [1]:
import numpy as np

# Define the matrices
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
B = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# 1. Index wise multiplication
index_wise_multiplication = A * B

# 2. Matrix multiplication
matrix_multiplication = np.dot(A, B.T)  

# 3. Add both matrices
addition = A + B

# 4. Subtract matrix B from A
subtraction = A - B

# 5. Divide Matrix B by A

division = np.divide(B, A)

# Print results
print("Index wise multiplication:\n", index_wise_multiplication)
print("Matrix multiplication:\n", matrix_multiplication)
print("Addition of both matrices:\n", addition)
print("Subtraction of matrix B from A:\n", subtraction)
print("Division of Matrix B by A:\n", division)



Index wise multiplication:
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
Matrix multiplication:
 [[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]
Addition of both matrices:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
Subtraction of matrix B from A:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Division of Matrix B by A:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# 12. Which function in Numpy can be use dto swap the byte order of an array?

In [2]:
# In NumPy, you can use the byteswap function to swap the byte order of an array. This function changes the byte order of the
# elements in the array from the native byte order to the alternative byte order.

import numpy as np

# Create a NumPy array with a specific byte order
arr = np.array([1, 2, 3, 4], dtype=np.int16)  # int16 uses 2 bytes per element

print("Original array:", arr)
print("Original byte order:", arr.dtype.byteorder)

# Swap the byte order
arr_swapped = arr.byteswap()

print("Array with swapped byte order:", arr_swapped)
print("Byte order after swap:", arr_swapped.dtype.byteorder)


Original array: [1 2 3 4]
Original byte order: =
Array with swapped byte order: [ 256  512  768 1024]
Byte order after swap: =


# 13. What is the significance of the np.linalg.inv function?

The np.linalg.inv function in NumPy is used to compute the inverse of a square matrix. The inverse of a matrix 𝐴 ,A is a matrix 𝐴-1 such that when multiplied together, they yield the identity matrix I. In mathematical terms:

𝐴.A-1 = A-1 .A = I

# Significance and Usage:
1. Solving Linear Systems: The inverse of a matrix is crucial for solving linear systems of equations of the form Ax=b. If A is invertible, you can find x by computing:

x=A −1b

2. Matrix Equations: In various mathematical and engineering applications, you might need to solve matrix equations or compute transformations. The matrix inverse is an essential tool in these contexts.

3. Determining Matrix Properties: The inverse can help in understanding the properties of a matrix. For example, if a matrix is singular (non-invertible), it means it does not have full rank or has linearly dependent rows/columns.

4. Numerical Methods: In numerical methods and algorithms, the inverse of a matrix is often used in optimization problems, control theory, and other fields.

In [4]:
# np.linalg.inv function
import numpy as np

# Define a square matrix
A = np.array([[1, 2], [3, 4]])

# Compute the inverse of the matrix
A_inv = np.linalg.inv(A)

print("Matrix A:\n", A)
print("Inverse of Matrix A:\n", A_inv)

# Verify the result by multiplying A with its inverse to get the identity matrix
identity_matrix = np.dot(A, A_inv)
print("Product of A and its inverse:\n", identity_matrix)


Matrix A:
 [[1 2]
 [3 4]]
Inverse of Matrix A:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Product of A and its inverse:
 [[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


# 14. What does the np.reshape function do, and how is it used?

The np.reshape function in NumPy is used to change the shape or dimensions of an existing array without changing its data. It allows you to create a new view of the data with a different shape, as long as the total number of elements remains the same.

* Key Features of np.reshape:

1. Change Dimensions: You can convert a 1-dimensional array into a 2-dimensional array, a 2-dimensional array into a 3-dimensional array, and so on, as long as the total number of elements remains consistent.

2. Data Preservation: The data in the array is not modified; only the shape of the array is altered.

3. Automatic Dimension Calculation: You can use -1 in one of the dimensions to let NumPy automatically calculate the size of that dimension based on the size of the other dimensions.



In [5]:
import numpy as np

# Create a 1D array
a = np.arange(12)
print("Original array:\n", a)

# Reshape it to a 2D array with 3 rows and 4 columns
b = np.reshape(a, (3, 4))
print("Reshaped to 2D array:\n", b)

# Reshape it to a 3D array with 2 layers, 3 rows, and 2 columns
c = np.reshape(a, (2, 3, 2))
print("Reshaped to 3D array:\n", c)

# Using -1 to automatically calculate one dimension
d = np.reshape(a, (3, -1))  # Here -1 means NumPy will calculate the size of this dimension
print("Reshaped with automatic dimension:\n", d)


Original array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped to 2D array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped to 3D array:
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
Reshaped with automatic dimension:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


# 15. What is broadcasting in Numpy?

In NumPy, broadcasting is a powerful technique that allows operations between arrays of different shapes. It automatically expands the smaller array to match the shape of the larger array, so that element-wise operations can be performed efficiently without explicitly replicating data.

* Rules for Broadcasting:

* Rule 1: If the arrays have a different number of dimensions, the shape of the smaller-dimensional array is padded with ones on the left side until both shapes are the same length.
* Rule 2: Two dimensions are compatible when:They are equal, or One of them is 1.
* Rule 3: If the dimensions are not compatible, broadcasting fails, and an error is raised.


In [6]:
#e.g to show broadcasting:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

vector = np.array([10, 20, 30])


In [8]:
result = matrix + vector #The vector is broadcast across each row of the matrix.
print(result)

[[11 22 33]
 [14 25 36]]
